Update main.yml
update macos versions used

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,7 +24,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [macos-11, macos-12, macos-13]
+        os: [macos-14, macos-15, macos-26]
 
     steps:
       - name: Checkout ports
@@ -32,11 +32,13 @@ jobs:
         with:
           fetch-depth: 64
           path: ports
+          show-progress: false
       - name: Checkout mpbb
         uses: actions/checkout@v6
         with:
           repository: macports/mpbb
           path: mpbb
+          show-progress: false
       - name: Bootstrap MacPorts
         run: . ports/.github/workflows/bootstrap.sh
       - name: Determine list of changed ports
@@ -69,23 +71,21 @@ jobs:
           echo "#### Changed Ports" >> $GITHUB_STEP_SUMMARY
 
           subportlist=""
-          for port in $portlist; do
-            echo "::group::Listing subports for ${port}"
-            new_subports=$(mpbb \
-                --work-dir /tmp/mpbb \
-                list-subports \
-                --archive-site= \
-                --archive-site-private= \
-                --include-deps=no \
-                "$port" \
+          echo "::group::Listing subports"
+          new_subports=$(mpbb \
+              --work-dir /tmp/mpbb \
+              list-subports \
+              --archive-site= \
+              --archive-site-private= \
+              --include-deps=no \
+              $portlist \
               | tr '\n' ' ')
-            for subport in $new_subports; do
-              echo "$subport"
-              echo "- ${subport}" >> $GITHUB_STEP_SUMMARY
-              subportlist="$subportlist $subport"
-            done
-            echo "::endgroup::"
+          for subport in $new_subports; do
+            echo "$subport"
+            echo "- ${subport}" >> $GITHUB_STEP_SUMMARY
+            subportlist="$subportlist $subport"
           done
+          echo "::endgroup::"
 
           echo "subportlist=${subportlist}" >> $GITHUB_OUTPUT
         env:
@@ -115,7 +115,7 @@ jobs:
               else
                 echo "##### ⚠️ ${subport}" >> $GITHUB_STEP_SUMMARY
               fi
-              printf '```\n%s```\n' "$messages" >> $GITHUB_STEP_SUMMARY
+              printf '```\n%s\n```\n' "$messages" >> $GITHUB_STEP_SUMMARY
 
               # See https://github.com/actions/toolkit/issues/193#issuecomment-605394935
               encoded_messages="port lint ${subport}:%0A"
@@ -207,6 +207,49 @@ jobs:
 
             echo "✅ Successfully built" >> $GITHUB_STEP_SUMMARY
             echo "::endgroup::"
+
+            echo "::group::Testing ${subport}"
+
+            test_fail=0
+            set +e
+            sudo mpbb \
+              --work-dir "$workdir" \
+              test-port \
+              --builtin-only \
+              "$subport"
+            test_exit=$?
+            set -e
+
+            if [ "$test_exit" -ne 0 ]; then
+              echo "::endgroup::"
+              echo "::error::Tests failed for ${subport}"
+
+              echo "❌ Tests failed, see the log for more details" >> $GITHUB_STEP_SUMMARY
+
+              # Not setting fail=1 as a 100% passing test suite is not considered
+              # essential to merge a PR.
+              test_fail=1
+            fi
+
+            test_msgs=$(port log --phase test --level warn "$subport")
+
+            if [ -n "$test_msgs" ]; then
+              echo "$test_msgs"
+              echo "⚠️ Test warnings" >> $GITHUB_STEP_SUMMARY
+
+              printf '```\n%s\n```\n' "$test_msgs" >> $GITHUB_STEP_SUMMARY
+
+              path=$(port file "$subport")
+              # See https://github.com/actions/toolkit/issues/193#issuecomment-605394935
+              encoded_messages="port test ${subport}:%0A"
+              encoded_messages+="$(echo "${test_msgs}" | sed -E 's/$/%0A/g' | tr -d '\n')"
+              echo "::warning file=${path#${PWD}/ports/},line=1,col=1::${encoded_messages}"
+            elif [ $test_fail -eq 0 ]; then
+                 echo "✅ Successfully tested" >> $GITHUB_STEP_SUMMARY
+            fi
+
+            echo "::endgroup::"
+
           done
 
           exit "$fail"
@@ -227,5 +270,5 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v6
         with:
-          name: logs-${{ matrix.os }}.zip
+          name: logs-${{ matrix.os }}
           path: /tmp/mpbb/*/logs
